<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateTableTimezones extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('timezones', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 80);
            $table->string('name_long', 100);
            $table->string('name_short', 5);
            $table->string('default_zone_name', 60);
            $table->tinyInteger('offset_hours');
            $table->unsignedTinyInteger('dst');
            $table->unsignedTinyInteger('status');
        });

        $this->fillTimezones();
    }

    private function fillTimezones()
    {
        $data = [
            [
                'name' => 'UTC-11',
                'name_short' => 'U',
                'offset_hours' => -11,
                'dst' => false,
                'name_long' => '(UTC-11:00) Coordinated Universal Time-11',
                'default_zone_name' => 'Pacific/Midway',
                'status' => 1,
            ],
            [
                'name' => 'Hawaiian Standard Time',
                'name_short' => 'HST',
                'offset_hours' => -10,
                'dst' => false,
                'name_long' => '(UTC-10:00) Hawaii',
                'default_zone_name' => 'Pacific/Honolulu',
                'status' => 1,
            ],
            [
                'name' => 'Alaskan Standard Time',
                'name_short' => 'AKDT',
                'offset_hours' => -8,
                'dst' => true,
                'name_long' => '(UTC-09:00) Alaska',
                'default_zone_name' => 'America/Anchorage',
                'status' => 1,
            ],
            [
                'name' => 'Pacific Standard Time (Mexico)',
                'name_short' => 'PDT',
                'offset_hours' => -7,
                'dst' => true,
                'name_long' => '(UTC-08:00) Baja California',
                'default_zone_name' => 'America/Santa_Isabel',
                'status' => 1,
            ],
            [
                'name' => 'Pacific Daylight Time',
                'name_short' => 'PDT',
                'offset_hours' => -7,
                'dst' => true,
                'name_long' => '(UTC-07:00) Pacific Time (US & Canada)',
                'default_zone_name' => 'America/Los_Angeles',
                'status' => 1,
            ],
            [
                'name' => 'Pacific Standard Time',
                'name_short' => 'PST',
                'offset_hours' => -8,
                'dst' => false,
                'name_long' => '(UTC-08:00) Pacific Time (US & Canada)',
                'default_zone_name' => 'America/Vancouver',
                'status' => 1,
            ],
            [
                'name' => 'US Mountain Standard Time',
                'name_short' => 'UMST',
                'offset_hours' => -7,
                'dst' => false,
                'name_long' => '(UTC-07:00) Arizona',
                'default_zone_name' => 'America/Creston',
                'status' => 1,
            ],
            [
                'name' => 'Mountain Standard Time (Mexico)',
                'name_short' => 'MDT',
                'offset_hours' => -6,
                'dst' => true,
                'name_long' => '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
                'default_zone_name' => 'America/Chihuahua',
                'status' => 1,
            ],
            [
                'name' => 'Mountain Standard Time',
                'name_short' => 'MDT',
                'offset_hours' => -6,
                'dst' => true,
                'name_long' => '(UTC-07:00) Mountain Time (US & Canada)',
                'default_zone_name' => 'America/Boise',
                'status' => 1,
            ],
            [
                'name' => 'Central America Standard Time',
                'name_short' => 'CAST',
                'offset_hours' => -6,
                'dst' => false,
                'name_long' => '(UTC-06:00) Central America',
                'default_zone_name' => 'America/Belize',
                'status' => 1,
            ],
            [
                'name' => 'Central Standard Time',
                'name_short' => 'CDT',
                'offset_hours' => -5,
                'dst' => true,
                'name_long' => '(UTC-06:00) Central Time (US & Canada)',
                'default_zone_name' => 'America/Chicago',
                'status' => 1,
            ],
            [
                'name' => 'Central Standard Time (Mexico)',
                'name_short' => 'CDT',
                'offset_hours' => -5,
                'dst' => true,
                'name_long' => '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
                'default_zone_name' => 'America/Bahia_Banderas',
                'status' => 1,
            ],
            [
                'name' => 'Canada Central Standard Time',
                'name_short' => 'CCST',
                'offset_hours' => -6,
                'dst' => false,
                'name_long' => '(UTC-06:00) Saskatchewan',
                'default_zone_name' => 'America/Regina',
                'status' => 1,
            ],
            [
                'name' => 'SA Pacific Standard Time',
                'name_short' => 'SPST',
                'offset_hours' => -5,
                'dst' => false,
                'name_long' => '(UTC-05:00) Bogota, Lima, Quito',
                'default_zone_name' => 'America/Bogota',
                'status' => 1,
            ],
            [
                'name' => 'Eastern Standard Time',
                'name_short' => 'EDT',
                'offset_hours' => -4,
                'dst' => true,
                'name_long' => '(UTC-05:00) Eastern Time (US & Canada)',
                'default_zone_name' => 'America/Detroit',
                'status' => 1,
            ],
            [
                'name' => 'US Eastern Standard Time',
                'name_short' => 'UEDT',
                'offset_hours' => -4,
                'dst' => true,
                'name_long' => '(UTC-05:00) Indiana (East)',
                'default_zone_name' => 'America/Indiana/Marengo',
                'status' => 1,
            ],
            [
                'name' => 'Venezuela Standard Time',
                'name_short' => 'VST',
                'offset_hours' => -4.5,
                'dst' => false,
                'name_long' => '(UTC-04:30) Caracas',
                'default_zone_name' => 'America/Caracas',
                'status' => 1,
            ],
            [
                'name' => 'Paraguay Standard Time',
                'name_short' => 'PYT',
                'offset_hours' => -4,
                'dst' => false,
                'name_long' => '(UTC-04:00) Asuncion',
                'default_zone_name' => 'America/Asuncion',
                'status' => 1,
            ],
            [
                'name' => 'Atlantic Standard Time',
                'name_short' => 'ADT',
                'offset_hours' => -3,
                'dst' => true,
                'name_long' => '(UTC-04:00) Atlantic Time (Canada)',
                'default_zone_name' => 'America/Glace_Bay',
                'status' => 1,
            ],
            [
                'name' => 'Central Brazilian Standard Time',
                'name_short' => 'CBST',
                'offset_hours' => -4,
                'dst' => false,
                'name_long' => '(UTC-04:00) Cuiaba',
                'default_zone_name' => 'America/Campo_Grande',
                'status' => 1,
            ],
            [
                'name' => 'SA Western Standard Time',
                'name_short' => 'SWST',
                'offset_hours' => -4,
                'dst' => false,
                'name_long' => '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
                'default_zone_name' => 'America/Anguilla',
                'status' => 1,
            ],
            [
                'name' => 'Pacific SA Standard Time',
                'name_short' => 'PSST',
                'offset_hours' => -4,
                'dst' => false,
                'name_long' => '(UTC-04:00) Santiago',
                'default_zone_name' => 'America/Santiago',
                'status' => 1,
            ],
            [
                'name' => 'Newfoundland Standard Time',
                'name_short' => 'NDT',
                'offset_hours' => -2.5,
                'dst' => true,
                'name_long' => '(UTC-03:30) Newfoundland',
                'default_zone_name' => 'America/St_Johns',
                'status' => 1,
            ],
            [
                'name' => 'E. South America Standard Time',
                'name_short' => 'ESAST',
                'offset_hours' => -3,
                'dst' => false,
                'name_long' => '(UTC-03:00) Brasilia',
                'default_zone_name' => 'America/Sao_Paulo',
                'status' => 1,
            ],
            [
                'name' => 'Argentina Standard Time',
                'name_short' => 'AST',
                'offset_hours' => -3,
                'dst' => false,
                'name_long' => '(UTC-03:00) Buenos Aires',
                'default_zone_name' => 'America/Argentina/La_Rioja',
                'status' => 1,
            ],
            [
                'name' => 'SA Eastern Standard Time',
                'name_short' => 'SEST',
                'offset_hours' => -3,
                'dst' => false,
                'name_long' => '(UTC-03:00) Cayenne, Fortaleza',
                'default_zone_name' => 'America/Araguaina',
                'status' => 1,
            ],
            [
                'name' => 'Greenland Standard Time',
                'name_short' => 'GDT',
                'offset_hours' => -3,
                'dst' => true,
                'name_long' => '(UTC-03:00) Greenland',
                'default_zone_name' => 'America/Godthab',
                'status' => 1,
            ],
            [
                'name' => 'Montevideo Standard Time',
                'name_short' => 'MST',
                'offset_hours' => -3,
                'dst' => false,
                'name_long' => '(UTC-03:00) Montevideo',
                'default_zone_name' => 'America/Montevideo',
                'status' => 1,
            ],
            [
                'name' => 'Bahia Standard Time',
                'name_short' => 'BST',
                'offset_hours' => -3,
                'dst' => false,
                'name_long' => '(UTC-03:00) Salvador',
                'default_zone_name' => 'America/Bahia',
                'status' => 1,
            ],
            [
                'name' => 'UTC-02',
                'name_short' => 'U',
                'offset_hours' => -2,
                'dst' => false,
                'name_long' => '(UTC-02:00) Coordinated Universal Time-02',
                'default_zone_name' => 'America/Noronha',
                'status' => 1,
            ],
            [
                'name' => 'Azores Standard Time',
                'name_short' => 'ADT',
                'offset_hours' => 0,
                'dst' => true,
                'name_long' => '(UTC-01:00) Azores',
                'default_zone_name' => 'America/Scoresbysund',
                'status' => 1,
            ],
            [
                'name' => 'Cape Verde Standard Time',
                'name_short' => 'CVST',
                'offset_hours' => -1,
                'dst' => false,
                'name_long' => '(UTC-01:00) Cape Verde Is.',
                'default_zone_name' => 'Atlantic/Cape_Verde',
                'status' => 1,
            ],
            [
                'name' => 'Morocco Standard Time',
                'name_short' => 'MDT',
                'offset_hours' => 1,
                'dst' => true,
                'name_long' => '(UTC) Casablanca',
                'default_zone_name' => 'Africa/Casablanca',
                'status' => 1,
            ],
            [
                'name' => 'UTC',
                'name_short' => 'UTC',
                'offset_hours' => 0,
                'dst' => false,
                'name_long' => '(UTC) Coordinated Universal Time',
                'default_zone_name' => 'America/Danmarkshavn',
                'status' => 1,
            ],
            [
                'name' => 'GMT Standard Time',
                'name_short' => 'GMT',
                'offset_hours' => 0,
                'dst' => false,
                'name_long' => '(UTC) Edinburgh, London',
                'default_zone_name' => 'Europe/Jersey',
                'status' => 1,
            ],
            [
                'name' => 'British Summer Time',
                'name_short' => 'BST',
                'offset_hours' => 1,
                'dst' => true,
                'name_long' => '(UTC+01:00) Edinburgh, London',
                'default_zone_name' => 'Europe/London',
                'status' => 1,
            ],
            [
                'name' => 'GMT Standard Time',
                'name_short' => 'GDT',
                'offset_hours' => 1,
                'dst' => true,
                'name_long' => '(UTC) Dublin, Lisbon',
                'default_zone_name' => 'Atlantic/Canary',
                'status' => 1,
            ],
            [
                'name' => 'Greenwich Standard Time',
                'name_short' => 'GST',
                'offset_hours' => 0,
                'dst' => false,
                'name_long' => '(UTC) Monrovia, Reykjavik',
                'default_zone_name' => 'Africa/Abidjan',
                'status' => 1,
            ],
            [
                'name' => 'W. Europe Standard Time',
                'name_short' => 'WEDT',
                'offset_hours' => 2,
                'dst' => true,
                'name_long' => '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
                'default_zone_name' => 'Arctic/Longyearbyen',
                'status' => 1,
            ],
            [
                'name' => 'Central Europe Standard Time',
                'name_short' => 'CEDT',
                'offset_hours' => 2,
                'dst' => true,
                'name_long' => '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
                'default_zone_name' => 'Europe/Belgrade',
                'status' => 1,
            ],
            [
                'name' => 'Romance Standard Time',
                'name_short' => 'RDT',
                'offset_hours' => 2,
                'dst' => true,
                'name_long' => '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
                'default_zone_name' => 'Europe/Brussels',
                'status' => 1,
            ],
            [
                'name' => 'Central European Standard Time',
                'name_short' => 'CEDT',
                'offset_hours' => 2,
                'dst' => true,
                'name_long' => '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
                'default_zone_name' => 'Europe/Sarajevo',
                'status' => 1,
            ],
            [
                'name' => 'W. Central Africa Standard Time',
                'name_short' => 'WCAST',
                'offset_hours' => 1,
                'dst' => false,
                'name_long' => '(UTC+01:00) West Central Africa',
                'default_zone_name' => 'Africa/Algiers',
                'status' => 1,
            ],
            [
                'name' => 'Namibia Standard Time',
                'name_short' => 'NST',
                'offset_hours' => 1,
                'dst' => false,
                'name_long' => '(UTC+01:00) Windhoek',
                'default_zone_name' => 'Africa/Windhoek',
                'status' => 1,
            ],
            [
                'name' => 'GTB Standard Time',
                'name_short' => 'GDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) Athens, Bucharest',
                'default_zone_name' => 'Europe/Bucharest',
                'status' => 1,
            ],
            [
                'name' => 'Middle East Standard Time',
                'name_short' => 'MEDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) Beirut',
                'default_zone_name' => 'Asia/Beirut',
                'status' => 1,
            ],
            [
                'name' => 'Egypt Standard Time',
                'name_short' => 'EST',
                'offset_hours' => 2,
                'dst' => false,
                'name_long' => '(UTC+02:00) Cairo',
                'default_zone_name' => 'Africa/Cairo',
                'status' => 1,
            ],
            [
                'name' => 'Syria Standard Time',
                'name_short' => 'SDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) Damascus',
                'default_zone_name' => 'Asia/Damascus',
                'status' => 1,
            ],
            [
                'name' => 'E. Europe Standard Time',
                'name_short' => 'EEDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) E. Europe',
                'default_zone_name' => 'Europe/Athens',
                'status' => 1,
            ],
            [
                'name' => 'South Africa Standard Time',
                'name_short' => 'SAST',
                'offset_hours' => 2,
                'dst' => false,
                'name_long' => '(UTC+02:00) Harare, Pretoria',
                'default_zone_name' => 'Africa/Blantyre',
                'status' => 1,
            ],
            [
                'name' => 'FLE Standard Time',
                'name_short' => 'FDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
                'default_zone_name' => 'Europe/Helsinki',
                'status' => 1,
            ],
            [
                'name' => 'Turkey Standard Time',
                'name_short' => 'TDT',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Istanbul',
                'default_zone_name' => 'Europe/Istanbul',
                'status' => 1,
            ],
            [
                'name' => 'Israel Standard Time',
                'name_short' => 'JDT',
                'offset_hours' => 3,
                'dst' => true,
                'name_long' => '(UTC+02:00) Jerusalem',
                'default_zone_name' => 'Asia/Jerusalem',
                'status' => 1,
            ],
            [
                'name' => 'Libya Standard Time',
                'name_short' => 'LST',
                'offset_hours' => 2,
                'dst' => false,
                'name_long' => '(UTC+02:00) Tripoli',
                'default_zone_name' => 'Africa/Tripoli',
                'status' => 1,
            ],
            [
                'name' => 'Jordan Standard Time',
                'name_short' => 'JST',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Amman',
                'default_zone_name' => 'Asia/Amman',
                'status' => 1,
            ],
            [
                'name' => 'Arabic Standard Time',
                'name_short' => 'AST',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Baghdad',
                'default_zone_name' => 'Asia/Baghdad',
                'status' => 1,
            ],
            [
                'name' => 'Kaliningrad Standard Time',
                'name_short' => 'KST',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+02:00) Kaliningrad',
                'default_zone_name' => 'Europe/Kaliningrad',
                'status' => 1,
            ],
            [
                'name' => 'Arab Standard Time',
                'name_short' => 'AST',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Kuwait, Riyadh',
                'default_zone_name' => 'Asia/Aden',
                'status' => 1,
            ],
            [
                'name' => 'E. Africa Standard Time',
                'name_short' => 'EAST',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Nairobi',
                'default_zone_name' => 'Africa/Addis_Ababa',
                'status' => 1,
            ],
            [
                'name' => 'Moscow Standard Time',
                'name_short' => 'MSK',
                'offset_hours' => 3,
                'dst' => false,
                'name_long' => '(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk',
                'default_zone_name' => 'Europe/Moscow',
                'status' => 1,
            ],
            [
                'name' => 'Samara Time',
                'name_short' => 'SAMT',
                'offset_hours' => 4,
                'dst' => false,
                'name_long' => '(UTC+04:00) Samara, Ulyanovsk, Saratov',
                'default_zone_name' => 'Europe/Samara',
                'status' => 1,
            ],
            [
                'name' => 'Iran Standard Time',
                'name_short' => 'IDT',
                'offset_hours' => 4.5,
                'dst' => true,
                'name_long' => '(UTC+03:30) Tehran',
                'default_zone_name' => 'Asia/Tehran',
                'status' => 1,
            ],
            [
                'name' => 'Arabian Standard Time',
                'name_short' => 'AST',
                'offset_hours' => 4,
                'dst' => false,
                'name_long' => '(UTC+04:00) Abu Dhabi, Muscat',
                'default_zone_name' => 'Asia/Dubai',
                'status' => 1,
            ],
            [
                'name' => 'Azerbaijan Standard Time',
                'name_short' => 'ADT',
                'offset_hours' => 5,
                'dst' => true,
                'name_long' => '(UTC+04:00) Baku',
                'default_zone_name' => 'Asia/Baku',
                'status' => 1,
            ],
            [
                'name' => 'Mauritius Standard Time',
                'name_short' => 'MST',
                'offset_hours' => 4,
                'dst' => false,
                'name_long' => '(UTC+04:00) Port Louis',
                'default_zone_name' => 'Indian/Mauritius',
                'status' => 1,
            ],
            [
                'name' => 'Georgian Standard Time',
                'name_short' => 'GET',
                'offset_hours' => 4,
                'dst' => false,
                'name_long' => '(UTC+04:00) Tbilisi',
                'default_zone_name' => 'Asia/Tbilisi',
                'status' => 1,
            ],
            [
                'name' => 'Caucasus Standard Time',
                'name_short' => 'CST',
                'offset_hours' => 4,
                'dst' => false,
                'name_long' => '(UTC+04:00) Yerevan',
                'default_zone_name' => 'Asia/Yerevan',
                'status' => 1,
            ],
            [
                'name' => 'Afghanistan Standard Time',
                'name_short' => 'AST',
                'offset_hours' => 4.5,
                'dst' => false,
                'name_long' => '(UTC+04:30) Kabul',
                'default_zone_name' => 'Asia/Kabul',
                'status' => 1,
            ],
            [
                'name' => 'West Asia Standard Time',
                'name_short' => 'WAST',
                'offset_hours' => 5,
                'dst' => false,
                'name_long' => '(UTC+05:00) Ashgabat, Tashkent',
                'default_zone_name' => 'Asia/Tashkent',
                'status' => 1,
            ],
            [
                'name' => 'Yekaterinburg Time',
                'name_short' => 'YEKT',
                'offset_hours' => 5,
                'dst' => false,
                'name_long' => '(UTC+05:00) Yekaterinburg',
                'default_zone_name' => 'Asia/Yekaterinburg',
                'status' => 1,
            ],
            [
                'name' => 'Pakistan Standard Time',
                'name_short' => 'PKT',
                'offset_hours' => 5,
                'dst' => false,
                'name_long' => '(UTC+05:00) Islamabad, Karachi',
                'default_zone_name' => 'Asia/Karachi',
                'status' => 1,
            ],
            [
                'name' => 'India Standard Time',
                'name_short' => 'IST',
                'offset_hours' => 5.5,
                'dst' => false,
                'name_long' => '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
                'default_zone_name' => 'Asia/Kolkata',
                'status' => 1,
            ],
            [
                'name' => 'Sri Lanka Standard Time',
                'name_short' => 'SLST',
                'offset_hours' => 5.5,
                'dst' => false,
                'name_long' => '(UTC+05:30) Sri Jayawardenepura',
                'default_zone_name' => 'Asia/Colombo',
                'status' => 1,
            ],
            [
                'name' => 'Nepal Standard Time',
                'name_short' => 'NST',
                'offset_hours' => 5.75,
                'dst' => false,
                'name_long' => '(UTC+05:45) Kathmandu',
                'default_zone_name' => 'Asia/Kathmandu',
                'status' => 1,
            ],
            [
                'name' => 'Central Asia Standard Time',
                'name_short' => 'CAST',
                'offset_hours' => 6,
                'dst' => false,
                'name_long' => '(UTC+06:00) Nur-Sultan (Astana)',
                'default_zone_name' => 'Antarctica/Vostok',
                'status' => 1,
            ],
            [
                'name' => 'Bangladesh Standard Time',
                'name_short' => 'BST',
                'offset_hours' => 6,
                'dst' => false,
                'name_long' => '(UTC+06:00) Dhaka',
                'default_zone_name' => 'Asia/Dhaka',
                'status' => 1,
            ],
            [
                'name' => 'Myanmar Standard Time',
                'name_short' => 'MST',
                'offset_hours' => 6.5,
                'dst' => false,
                'name_long' => '(UTC+06:30) Yangon (Rangoon)',
                'default_zone_name' => 'Asia/Rangoon',
                'status' => 1,
            ],
            [
                'name' => 'SE Asia Standard Time',
                'name_short' => 'SAST',
                'offset_hours' => 7,
                'dst' => false,
                'name_long' => '(UTC+07:00) Bangkok, Hanoi, Jakarta',
                'default_zone_name' => 'Asia/Bangkok',
                'status' => 1,
            ],
            [
                'name' => 'N. Central Asia Standard Time',
                'name_short' => 'NCAST',
                'offset_hours' => 7,
                'dst' => false,
                'name_long' => '(UTC+07:00) Novosibirsk',
                'default_zone_name' => 'Asia/Novosibirsk',
                'status' => 1,
            ],
            [
                'name' => 'China Standard Time',
                'name_short' => 'CST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
                'default_zone_name' => 'Asia/Hong_Kong',
                'status' => 1,
            ],
            [
                'name' => 'North Asia Standard Time',
                'name_short' => 'NAST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Krasnoyarsk',
                'default_zone_name' => 'Asia/Krasnoyarsk',
                'status' => 1,
            ],
            [
                'name' => 'Singapore Standard Time',
                'name_short' => 'MPST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Kuala Lumpur, Singapore',
                'default_zone_name' => 'Asia/Singapore',
                'status' => 1,
            ],
            [
                'name' => 'W. Australia Standard Time',
                'name_short' => 'WAST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Perth',
                'default_zone_name' => 'Australia/Perth',
                'status' => 1,
            ],
            [
                'name' => 'Taipei Standard Time',
                'name_short' => 'TST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Taipei',
                'default_zone_name' => 'Asia/Taipei',
                'status' => 1,
            ],
            [
                'name' => 'Ulaanbaatar Standard Time',
                'name_short' => 'UST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Ulaanbaatar',
                'default_zone_name' => 'Asia/Ulaanbaatar',
                'status' => 1,
            ],
            [
                'name' => 'North Asia East Standard Time',
                'name_short' => 'NAEST',
                'offset_hours' => 8,
                'dst' => false,
                'name_long' => '(UTC+08:00) Irkutsk',
                'default_zone_name' => 'Asia/Irkutsk',
                'status' => 1,
            ],
            [
                'name' => 'Japan Standard Time',
                'name_short' => 'JST',
                'offset_hours' => 9,
                'dst' => false,
                'name_long' => '(UTC+09:00) Osaka, Sapporo, Tokyo',
                'default_zone_name' => 'Asia/Tokyo',
                'status' => 1,
            ],
            [
                'name' => 'Korea Standard Time',
                'name_short' => 'KST',
                'offset_hours' => 9,
                'dst' => false,
                'name_long' => '(UTC+09:00) Seoul',
                'default_zone_name' => 'Asia/Seoul',
                'status' => 1,
            ],
            [
                'name' => 'Cen. Australia Standard Time',
                'name_short' => 'CAST',
                'offset_hours' => 9.5,
                'dst' => false,
                'name_long' => '(UTC+09:30) Adelaide',
                'default_zone_name' => 'Australia/Adelaide',
                'status' => 1,
            ],
            [
                'name' => 'AUS Central Standard Time',
                'name_short' => 'ACST',
                'offset_hours' => 9.5,
                'dst' => false,
                'name_long' => '(UTC+09:30) Darwin',
                'default_zone_name' => 'Australia/Darwin',
                'status' => 1,
            ],
            [
                'name' => 'E. Australia Standard Time',
                'name_short' => 'EAST',
                'offset_hours' => 10,
                'dst' => false,
                'name_long' => '(UTC+10:00) Brisbane',
                'default_zone_name' => 'Australia/Brisbane',
                'status' => 1,
            ],
            [
                'name' => 'AUS Eastern Standard Time',
                'name_short' => 'AEST',
                'offset_hours' => 10,
                'dst' => false,
                'name_long' => '(UTC+10:00) Canberra, Melbourne, Sydney',
                'default_zone_name' => 'Australia/Melbourne',
                'status' => 1,
            ],
            [
                'name' => 'West Pacific Standard Time',
                'name_short' => 'WPST',
                'offset_hours' => 10,
                'dst' => false,
                'name_long' => '(UTC+10:00) Guam, Port Moresby',
                'default_zone_name' => 'Pacific/Guam',
                'status' => 1,
            ],
            [
                'name' => 'Tasmania Standard Time',
                'name_short' => 'TST',
                'offset_hours' => 10,
                'dst' => false,
                'name_long' => '(UTC+10:00) Hobart',
                'default_zone_name' => 'Australia/Hobart',
                'status' => 1,
            ],
            [
                'name' => 'Yakutsk Standard Time',
                'name_short' => 'YST',
                'offset_hours' => 9,
                'dst' => false,
                'name_long' => '(UTC+09:00) Yakutsk',
                'default_zone_name' => 'Asia/Yakutsk',
                'status' => 1,
            ],
            [
                'name' => 'Central Pacific Standard Time',
                'name_short' => 'CPST',
                'offset_hours' => 11,
                'dst' => false,
                'name_long' => '(UTC+11:00) Solomon Is., New Caledonia',
                'default_zone_name' => 'Pacific/Efate',
                'status' => 1,
            ],
            [
                'name' => 'Vladivostok Standard Time',
                'name_short' => 'VST',
                'offset_hours' => 11,
                'dst' => false,
                'name_long' => '(UTC+11:00) Vladivostok',
                'default_zone_name' => 'Asia/Vladivostok',
                'status' => 1,
            ],
            [
                'name' => 'New Zealand Standard Time',
                'name_short' => 'NZST',
                'offset_hours' => 12,
                'dst' => false,
                'name_long' => '(UTC+12:00) Auckland, Wellington',
                'default_zone_name' => 'Pacific/Auckland',
                'status' => 1,
            ],
            [
                'name' => 'UTC+12',
                'name_short' => 'U',
                'offset_hours' => 12,
                'dst' => false,
                'name_long' => '(UTC+12:00) Coordinated Universal Time+12',
                'default_zone_name' => 'Pacific/Funafuti',
                'status' => 1,
            ],
            [
                'name' => 'Fiji Standard Time',
                'name_short' => 'FST',
                'offset_hours' => 12,
                'dst' => false,
                'name_long' => '(UTC+12:00) Fiji',
                'default_zone_name' => 'Pacific/Fiji',
                'status' => 1,
            ],
            [
                'name' => 'Magadan Standard Time',
                'name_short' => 'MST',
                'offset_hours' => 12,
                'dst' => false,
                'name_long' => '(UTC+12:00) Magadan',
                'default_zone_name' => 'Asia/Anadyr',
                'status' => 1,
            ],
            [
                'name' => 'Kamchatka Standard Time',
                'name_short' => 'KDT',
                'offset_hours' => 13,
                'dst' => true,
                'name_long' => '(UTC+12:00) Kamchatka',
                'default_zone_name' => 'Asia/Kamchatka',
                'status' => 1,
            ],
            [
                'name' => 'Tonga Standard Time',
                'name_short' => 'TST',
                'offset_hours' => 13,
                'dst' => false,
                'name_long' => "(UTC+13:00) Nuku'alofa",
                'default_zone_name' => 'Pacific/Enderbury',
                'status' => 1,
            ],
            [
                'name' => 'Samoa Standard Time',
                'name_short' => 'SST',
                'offset_hours' => 13,
                'dst' => false,
                'name_long' => '(UTC+13:00) Samoa',
                'default_zone_name' => 'Pacific/Apia',
                'status' => 1,
            ],
        ];

        DB::table('timezones')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('timezones');
    }
}
